name: Build and Test Shigu Docker Image
on: 
  push:
    branches: 
      master
jobs: 
  docker_build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build And Push Melodic Docker Image
        env:
          image_name: choate1990/ros
          tag: foxy-desktop
        run: |
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          cd foxy
          docker build -t $image_name:$tag . --no-cache
          docker push $image_name:$tag
          